// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fefesixiiamcdqsetzcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlZmVzaXhpaWFtY2Rxc2V0emNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMzI4ODksImV4cCI6MjA2NDYwODg4OX0.Lt9SgXlcs3lwAgdGXvk7Z7UEijI4Prd77jaDr9OK6JM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);